---
title: "RESTORE VEGETATION SURVEYS"
output: 
  flexdashboard::flex_dashboard:
    logo: www/tarponlogo.png
    social: menu
    source_code: "https://github.com/tbep-tech/restore-surveys"
runtime: shiny
css: styles.css
---
  
```{r setup, include=F}
knitr::opts_chunk$set(echo = F, warning = F, message = F)

library(here)
library(ggplot2)
library(tidyr)
library(dplyr)
library(reactable)
library(shiny)
library(lubridate)
library(stringr)
library(forcats)
library(htmltools)
library(htmlwidgets)
library(shinyWidgets)
library(plotly)

source(here('R/funcs.R'))

load(file = here('data/vegdat.RData'))
load(file = here('data/treedat.RData'))

thm <- theme_minimal(base_size = 16) + 
  theme(
    panel.grid.minor = element_blank() 
  )

# initial options
sitopt <- unique(vegdat$site)
sppopt <- unique(vegdat$species) %>% 
  sort %>% 
  .[!. %in% c('Boardwalk', 'none/detritus', 'Open Water', 'Unknown')]

# # style file
# styles <- readLines('https://raw.githubusercontent.com/tbep-tech/css-styling/master/styles.css')
# writeLines(styles, 'styles.css')
```

```{r reactives}
# tabular vegetation summary by site
vegtab1 <- reactive({
  
  # input
  sitsel2 <- input$sitsel2
  zonsel2 <- input$zonsel2
  varsel1 <- input$varsel1
  
  req(zonsel2)
  
  out <- sitezonesum_tab(vegdat, site = sitsel2, zone = zonsel2, var = varsel1)
  
  return(out)
  
})

# tabular vegetation summary by site, download
vegtabdl1 <- reactive({

  # input
  sitsel2 <- input$sitsel2
  zonsel2 <- input$zonsel2
  varsel1 <- input$varsel1

  req(zonsel2)

  out <- sitezonesum_fun(vegdat, site = sitsel2, zone = zonsel2, var = varsel1)

  return(out)

})

# plot vegetation summary by site
vegplo2 <- reactive({
  
  # input
  sitsel2 <- input$sitsel2
  zonsel2 <- input$zonsel2
  varsel1 <- input$varsel1
  vegsel <- input$vegsel
  
  req(zonsel2)
  req(vegsel)
  
  out <- sitesum_plo(vegdat, site = sitsel2, vegsel = vegsel, var = varsel1, zone = zonsel2, thm = thm)
  
  return(out)
  
})

# tabular tree summary by site
treetab1 <- reactive({
  
  # input
  sitsel3 <- input$sitsel3
  zonsel3 <- input$zonsel3
  varsel2 <- input$varsel2
  aggsel <- input$aggsel
  
  req(zonsel3)
  
  out <- treesum_tab(treedat, site = sitsel3, byspecies = aggsel, zone = zonsel3, var = varsel2)
  
  return(out)
  
})

# tabular tree summary by site download
treetabdl1 <- reactive({

  # input
  sitsel3 <- input$sitsel3
  zonsel3 <- input$zonsel3
  varsel2 <- input$varsel2
  aggsel <- input$aggsel

  req(zonsel3)

  out <- treesum_fun(treedat, sitsel3, byspecies = aggsel, zone = zonsel3, var = varsel2) %>%
    pivot_wider(names_from = 'trt', values_from = 'val', values_fill = NA) %>%
    arrange(zone)

  return(out)

})

# plot tree summary by site
treeplo1 <- reactive({
  
  # input
  sitsel3 <- input$sitsel3
  zonsel3 <- input$zonsel3
  varsel2 <- input$varsel2
  aggsel <- input$aggsel
  dgesel <- input$dgesel
  tresel <- input$tresel
  
  req(zonsel3)
  
  out <- treesum_plo(treedat, site = sitsel3, byspecies = aggsel, zone = zonsel3, var = varsel2, dodge = dgesel, thm = thm)
  
  return(out)
  
})

# summary plot by species, all sites
allplo1 <- reactive({
  
  # input
  sppsel <- input$sppsel
  stesel <- input$stesel
  varsel3 <- input$varsel3
  
  req(stesel)
  
  out <- sppsum_plo(vegdat, sp = sppsel, var = varsel3, sitefct = stesel, thm = thm)
  
  return(out)
  
})
```

```{r download}
# download veg table
output$vegtabdl1 <- downloadHandler(
  filename = function(){'vegetation_summary.csv'},
  content = function(file){

    # inputs
    vegtabdl1 <- vegtabdl1()

    write.csv(vegtabdl1, file, quote = T, row.names = F)

  }
)

# download tree table
output$treetabdl1 <- downloadHandler(
  filename = function(){'tree_summary.csv'},
  content = function(file){

    # inputs
    treetabdl1 <- treetabdl1()

    write.csv(treetabdl1, file, quote = T, row.names = F)

  }
)
```

1 VEGETATION SURVEYS {data-navmenu="PAGE SELECTION"}
=======================================================================
  
Column {data-width=200 .tabset .tabset-fade}
-----------------------------------------------------------------------
  
### Summary options
  
```{r}
column(12,  
       selectInput('sitsel2', 'Select site:', choices = sitopt, width = '100%')
)
column(12, 
       renderUI({
         
         # input
         sitsel2 <- input$sitsel2
         
         tosel <- vegdat %>% 
           filter(site %in% !!sitsel2) %>% 
           mutate(zone = factor(zone, levels = sort(unique(zone)))) %>% 
           pull(zone) %>% 
           levels
         
         selectInput('zonsel2', 'Select zone:', choices = tosel, selectize = T, multiple = T, selected = tosel, width = '100%')
         
       })
)
column(12, 
       selectInput('varsel1', 'Select summary variable:', choices = list('Freq. Occ (%)' = 'fo', 'Basal cover (%)' = 'cover'), width = '100%')
)
```

### About

Column {.tabset .tabset-fade data-width=700}
-----------------------------------------------------------------------
  
### Species summary
  
```{r}
output$vegplo2 <- renderPlotly(vegplo2())
fillCol(flex = c(NA, 1),
  column(12, 
    column(3, selectInput('spptyp', 'Select species by:', choices = c('Top n', 'Names'), width = '100%')), 
    column(3, 
    renderUI({
      
      # inputs
      spptyp <- input$spptyp
      sitsel2 <- input$sitsel2
      
      if(spptyp == 'Names'){
        
        tosel <- vegdat %>% 
          filter(site %in% sitsel2) %>%  
          pull(species) %>% 
          unique %>% 
          sort
        
        sel <- tosel[1:min(length(tosel), 10)]
        
        out <- pickerInput('vegsel', 'Select species to show:', choices = tosel, selected = sel, multiple = T, 
                           options = list(`actions-box` = TRUE))
        
      }
      
      if(spptyp == 'Top n')
        out <- sliderInput('vegsel', 'Select number of species:', min = 1, max = 30, step = 1, value = 10, width = '100%')
      
      return(out)
      
    })     
    )
  ),  
  plotlyOutput('vegplo2')
)
```

### Tabular summary

```{r}
output$vegtab1 <- renderReactable(vegtab1())
fillCol(flex = c(NA, 1),
  downloadBttn('vegtabdl1', 'Download data', style = 'simple', block = T, color = 'success'),
  reactableOutput('vegtab1')
)
```

2 TREE SURVEYS {data-navmenu="PAGE SELECTION"}
=======================================================================
  
Column {data-width=200 .tabset .tabset-fade}
-----------------------------------------------------------------------
  
### Summary options

```{r}
column(12,  
  selectInput('sitsel3', 'Select site:', choices = sitopt, width = '100%')
)
column(12, 
  renderUI({
   
    # input
    sitsel3 <- input$sitsel3
    
    tosel <- treedat %>% 
      filter(site %in% !!sitsel3) %>% 
      mutate(zone = factor(zone, levels = sort(unique(zone)))) %>% 
      pull(zone) %>% 
      levels
    
    selectInput('zonsel3', 'Select zone:', choices = tosel, selectize = T, multiple = T, selected = tosel, width = '100%')

  })
)
column(12, 
  selectInput('varsel2', 'Select summary variable:', 
             choices = list(
               'Absolute species density (trees/m2)' = 'trees_m2',
               'Absolute species density (trees/ha)'= 'trees_ha', 
               'Species average basal area (cm2/m2)' =  'cm2_m2',
               'Species absolute cover (m2/ha)' = 'm2_ha', 
               'Relative cover (%)' = 'relcov_per', 
               'Tree height (m)' = 'tree_height'
             ),
             width = '100%'
  )
)
column(12, 
  materialSwitch(inputId = 'aggsel', label = 'Show results by species?', value = T, width = '100%')
)
column(12, 
  materialSwitch(inputId = 'dgesel', label = 'Separate columns by species?', value = T, width = '100%')
)
```

### About

Column {.tabset .tabset-fade data-width=700}
-----------------------------------------------------------------------
  
### Species by distance
  
```{r}
output$treeplo1 <- renderPlotly(treeplo1())
fillCol(flex = c(NA, 1),
  column(12, 
    column(3, selectInput('spptyp2', 'Select species by:', choices = c('Top n', 'Names'), width = '100%')), 
    column(3, 
      renderUI({
        
        # inputs
        spptyp2 <- input$spptyp2
        sitsel3 <- input$sitsel3
        
        if(spptyp2 == 'Names'){
         
           tosel <- treedat %>% 
             filter(site %in% sitsel3) %>%  
             pull(species) %>% 
             unique %>% 
             sort
           
           sel <- tosel[1:min(length(tosel), 10)]
  
           out <- pickerInput('tresel', 'Select species to show:', choices = tosel, selected = sel, multiple = T, 
                              options = list(`actions-box` = TRUE))
           
        }
        
        if(spptyp2 == 'Top n')
          out <- sliderInput('tresel', 'Select number of species:', min = 1, max = 20, step = 1, value = 10, width = '100%')
      
        return(out)
        
      })     
    )
  ),
  plotlyOutput('treeplo1')
)
```

### Tabular summary

```{r}
output$treetab1 <- renderReactable(treetab1())
fillCol(flex = c(NA, 1),
  downloadBttn('treetabdl1', 'Download data', style = 'simple', block = T, color = 'success'),
  reactableOutput('treetab1')
)
```

3 BETWEEN SITE COMPARISONS {data-navmenu="PAGE SELECTION"}
=======================================================================
  
Column {data-width=200 .tabset .tabset-fade}
-----------------------------------------------------------------------
  
### Summary options
  
Summaries are for vegetation data only. 

```{r}
column(12, 
       selectInput('sppsel', 'Select species:', choices = sppopt, selected = 'Avicennia germinans', width = '100%')
)
column(12, 
       renderUI({
         
         # input
         sppsel <- input$sppsel
         
         tosel <- vegdat %>% 
           filter(species %in% !!sppsel) %>% 
           pull(site) %>% 
           unique %>% 
           sort
         
         selectInput('stesel', 'Select site:', choices = tosel, selectize = T, multiple = T, selected = tosel, width = '100%')
         
       })
)
column(12, 
       selectInput('varsel3', 'Select summary variable:', choices = list('Freq. Occ (%)' = 'fo', 'Basal cover (%)' = 'cover'), width = '100%')
)
```

### About

Column {.tabset .tabset-fade data-width=700}
-----------------------------------------------------------------------
  
### Species by zone
  
```{r}
output$allplo1 <- renderPlotly(allplo1())
plotlyOutput('allplo1')
```
